#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS == 'android':
		return

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']

	install_path = bld.env.BINDIR

	if bld.env.DEST_OS == 'wasm':
		# main.cpp must pull the browser-backed retail bridge into the final
		# MAIN_MODULE. Keep both in one archive member so runtime-dlopen symbols
		# cannot be discarded as an otherwise-unreferenced static-library object.
		source = ['render360_wasm_main.cpp']
		bld.stlib(
			source   = source,
			target   = PROJECT_NAME,
			name	 = PROJECT_NAME,
			features = 'c cxx',
			includes = includes,
			defines  = defines,
			use      = libs,
			subsystem = bld.env.MSVC_SUBSYSTEM,
			idx      = bld.get_taskgen_count()
		)
	else:
		bld(
			source   = source,
			target   = PROJECT_NAME,
			name	 = PROJECT_NAME,
			features = 'c cxx cxxprogram',
			includes = includes,
			defines  = defines,
			use      = libs,
			install_path = install_path,
			subsystem = bld.env.MSVC_SUBSYSTEM,
			idx      = bld.get_taskgen_count()
		)

