#!/usr/bin/env python3
"""Fail the build if a side module needs a C++ symbol nobody provides.

Every Source module is a separate wasm file that the browser links at
runtime. If one module imports a symbol that no other module (or the main
module) exports, the page aborts on the phone with
"undefined symbol ..." -- which is how SIDE_MODULE=2 broke the iPhone
build (CThread::Start). This reads the import and export sections of
every .wasm/.so in a directory and reports unresolved imports.

Emscripten treats the two kinds of import differently (src/lib/libdylink.js):

- GOT.mem / GOT.func imports (data, and functions whose address is taken)
  are checked by reportUndefinedSymbols when a module loads. A missing one
  aborts the page on the spot. These are hard failures here.
- env.* function imports get a stub that resolves on first call, so a
  missing one only fails if that code path actually runs. These are listed
  as lazy, not failed: Source has some on tool-only paths (benchmark upload,
  model-preview panels) that the original web port shipped with too.
- invoke_* helpers are generated by the runtime on demand; ignored.

Usage: check_wasm_links.py build/install
"""
import os
import re
import sys


def uleb(b, i):
    result = shift = 0
    while True:
        byte = b[i]; i += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, i
        shift += 7


def name(b, i):
    n, i = uleb(b, i)
    return b[i:i + n].decode('utf-8', 'replace'), i + n


def limits(b, i):
    flags = b[i]; i += 1
    _, i = uleb(b, i)
    if flags & 1:
        _, i = uleb(b, i)
    return i


def parse(path):
    b = open(path, 'rb').read()
    if b[:4] != b'\0asm':
        raise ValueError(f'{path}: not a wasm module')
    i, imports, exports = 8, [], set()
    while i < len(b):
        sid = b[i]; i += 1
        size, i = uleb(b, i)
        end = i + size
        if sid == 2:
            j = i
            count, j = uleb(b, j)
            for _ in range(count):
                mod, j = name(b, j)
                field, j = name(b, j)
                kind = b[j]; j += 1
                if kind == 0:
                    _, j = uleb(b, j)
                elif kind == 1:
                    j += 1; j = limits(b, j)
                elif kind == 2:
                    j = limits(b, j)
                elif kind == 3:
                    j += 2
                elif kind == 4:
                    j += 1; _, j = uleb(b, j)
                else:
                    raise ValueError(f'{path}: unknown import kind {kind}')
                imports.append((mod, field, kind))
        elif sid == 7:
            j = i
            count, j = uleb(b, j)
            for _ in range(count):
                field, j = name(b, j)
                j += 1
                _, j = uleb(b, j)
                exports.add(field)
        i = end
    return imports, exports


# Provided by the dynamic linker / runtime itself, never by a module export.
RUNTIME = {'memory', '__indirect_function_table', '__stack_pointer',
           '__memory_base', '__table_base', '__tls_base'}


def main(directory):
    files = sorted(f for f in os.listdir(directory)
                   if f.endswith('.so') or f == 'hl2_launcher.wasm')
    if not files:
        print(f'no wasm modules in {directory}'); return 2
    mods = {f: parse(os.path.join(directory, f)) for f in files}
    provided = set().union(*(e for _, e in mods.values()))

    js = ''
    js_path = os.path.join(directory, 'hl2_launcher.js')
    if os.path.exists(js_path):
        js = open(js_path, encoding='utf-8', errors='replace').read()
    js_names = set(re.findall(r'\b_?([A-Za-z_][A-Za-z0-9_$]*)\b', js))

    fatal = lazy = checked = 0
    for f, (imports, _) in mods.items():
        for mod, field, kind in imports:
            if mod not in ('env', 'GOT.func', 'GOT.mem') or field in RUNTIME:
                continue
            if field.startswith('invoke_'):
                continue
            checked += 1
            if field in provided:
                continue
            if mod.startswith('GOT.'):
                fatal += 1
                print(f'FATAL  {f}: {mod}.{field}  (aborts at load)')
            elif field not in js_names and field.lstrip('_') not in js_names:
                lazy += 1
                print(f'lazy   {f}: {mod}.{field}  (fails only if called)')
    print(f'wasm link closure: {len(files)} modules, {checked} imports checked, '
          f'{fatal} load-fatal unresolved, {lazy} lazy unresolved')
    return 1 if fatal else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else 'build/install'))
